### ISSUE TITLE
TypeError: Cannot set property 'esriLoader' of undefined

### ISSUE THREAD

**Issue by Kunal1985** [davetimmins/create-react-app-esri-loader#1]
Hi, I am not able to successfully execute test for React components which contain esri components

Please see the attached files
[Donor.zip](https://github.com/davetimmins/create-react-app-esri-loader/files/1134390/Donor.zip)
Donor.js > contains arcgis components using esri-loader and dojo
Donor.test.js > Contain simple unit test for Donor component

Below the stack trace
`jest -u`
` FAIL  app\test\Donor.test.js
  ● Component: Donor rendered`

    TypeError: Cannot set property 'esriLoader' of undefined

      at bootstrap (node_modules/esri-loader/dist/esri-loader.js:32:34)
      at EsriLoader.componentDidMount (node_modules/esri-loader-react/lib/index.js:37:33)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:209:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:156:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:143:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
      at Object.<anonymous> (app/test/Donor.test.js:8:47)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
Can you please tell me how to proceed or send me a reference to resolve the same.

**Thanks & Regards,**
Kunal

**Comment by davetimmins** [comment]
That error looks like it's coming from esri-loader rather than this project so you might want to try there, either way you should provide a complete working repro rather than just a portion of your code otherwise it isn't representative of the issue at hand.

**Comment by davetimmins** [comment]
Also, it may just be how the default testing is setup for CRA sites. I can repro this error but using a different testing framework I can run it ok, so could be to do with running headless.

**Comment by Kunal1985** [comment]
Can you please let me know using which testing framework you can run it successfully.

**Comment by davetimmins** [comment]
That was with karma

**Comment by Kunal1985** [comment]
I have uploaded my entire code
https://github.com/Kunal1985/blood-connect
I need to enable tests for this project esp. for React-Esri components, so that I have a continuous unit test ready for each component.
Can you direct me how to proceed here, am clueless on how to proceed.

**Comment by davetimmins** [comment]
Have a look now, I've updated the test to run using enzyme so it passes now. See https://jest-bot.github.io/jest/docs/tutorial-react.html#dom-testing for more info.

**Comment by davetimmins** [comment]
Closing this as the original issue is resolved

**Comment by Kunal1985** [comment]
Thanks!
